# sistem-informasi-organisasi/docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_projek
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # <--- TAMBAHKAN BARIS INI
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge